"""schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-15 13:10:57.320160

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='routing_job_status'), server_default='queued', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unassigned_order_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('bug_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_jobs'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('client', 'driver', 'dispatcher', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='user_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('client_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('needs_escort', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('default_addresses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_client_profiles'))
    )
    op.create_table('drivers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('vehicle_model', sa.Text(), nullable=True),
    sa.Column('plate', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=True),
    sa.Column('shift_end', sa.Time(), nullable=True),
    sa.Column('home_lat', sa.Float(precision=53), nullable=True),
    sa.Column('home_lon', sa.Float(precision=53), nullable=True),
    sa.CheckConstraint('capacity IN (4, 6)', name=op.f('ck_drivers_capacity_4_or_6')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drivers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_drivers'))
    )
    op.create_table('route_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='plan_status'), server_default='draft', nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('routing_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_route_plans_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_plans'))
    )
    op.create_table('driver_lunches',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.user_id'], name=op.f('fk_driver_lunches_driver_id_drivers')),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], name=op.f('fk_driver_lunches_plan_id_route_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'driver_id', name='pk_driver_lunches')
    )
    op.create_table('driver_track_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.user_id'], name=op.f('fk_driver_track_history_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', 'ts', name='pk_driver_track_history'),
    postgresql_partition_by='RANGE (ts)'
    )
    op.create_index('ix_track_history_driver_ts', 'driver_track_history', ['driver_id', 'ts'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('desired_time', sa.Time(), nullable=False),
    sa.Column('pickup_addr', sa.Text(), nullable=True),
    sa.Column('pickup_lat', sa.Float(precision=53), nullable=True),
    sa.Column('pickup_lon', sa.Float(precision=53), nullable=True),
    sa.Column('dropoff_addr', sa.Text(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(precision=53), nullable=True),
    sa.Column('dropoff_lon', sa.Float(precision=53), nullable=True),
    sa.Column('escort', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('seats', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('twin_group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('created', 'scheduled', 'assigned', 'driver_en_route', 'picked_up', 'completed', 'cancelled', 'exception', name='order_status'), server_default='created', nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seats IN (1, 2)', name=op.f('ck_orders_seats_1_or_2')),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.user_id'], name=op.f('fk_orders_client_id_client_profiles')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('external_id', name=op.f('uq_orders_external_id'))
    )
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_index('ix_orders_service_date_status', 'orders', ['service_date', 'status'], unique=False)
    op.create_index('ix_orders_twin_group_id', 'orders', ['twin_group_id'], unique=False, postgresql_where=sa.text('twin_group_id IS NOT NULL'))
    op.create_table('route_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('trip', 'run', name='assignment_kind'), nullable=False),
    sa.Column('order_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('planned_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_dropoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_seq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dropoff_seq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.user_id'], name=op.f('fk_route_assignments_driver_id_drivers')),
    sa.ForeignKeyConstraint(['plan_id'], ['route_plans.id'], name=op.f('fk_route_assignments_plan_id_route_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_assignments')),
    sa.UniqueConstraint('plan_id', 'driver_id', 'seq', name='uq_assignment_plan_driver_seq')
    )
    op.create_index(op.f('ix_route_assignments_plan_id'), 'route_assignments', ['plan_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.Enum('created', 'scheduled', 'assigned', 'driver_en_route', 'picked_up', 'completed', 'cancelled', 'exception', name='order_status'), nullable=True),
    sa.Column('to_status', sa.Enum('created', 'scheduled', 'assigned', 'driver_en_route', 'picked_up', 'completed', 'cancelled', 'exception', name='order_status'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_order_events_actor_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index('ix_order_events_order_ts', 'order_events', ['order_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_order_events_order_ts", table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_route_assignments_plan_id"), table_name="route_assignments")
    op.drop_table("route_assignments")
    op.drop_index("ix_orders_twin_group_id", table_name="orders")
    op.drop_index("ix_orders_service_date_status", table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_track_history_driver_ts", table_name="driver_track_history")
    op.drop_table("driver_track_history")
    op.drop_table("driver_lunches")
    op.drop_table("route_plans")
    op.drop_table("drivers")
    op.drop_table("client_profiles")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_table("users")
    op.drop_table("routing_jobs")
    for enum_name in (
        "order_status",
        "plan_status",
        "assignment_kind",
        "routing_job_status",
        "user_role",
        "user_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
